# Generated by Django 5.2.13 on 2026-04-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
